### ISSUE TITLE
Missing "sup-dom-plugin" dependency when installing via NPM

### ISSUE THREAD

**Issue by torleif** [florentpoujol/superpowers-threejs-plugin#1]
npm WARN install Couldn't install optional dependency: Registry returned 404 for GET on https://registry.npmjs.org/sup-dom-plugin

it seems the sup-dom-plugin has been renamed

**Comment by florentpoujol** [comment]
Indeed, my mistake, you need this plugin too :
https://github.com/florentpoujol/superpowers-game-dom-plugin

I will fix that, and make it clearer in the readme, thanks !

**Comment by florentpoujol** [comment]
I removed the dependency and added a warning message after the installation via `npm`.
I think it's more practical that way.

**Comment by torleif** [comment]
thanks!
