### ISSUE TITLE
Seems to be missing lots compared to superpowers

### ISSUE THREAD

**Issue by ken-sands** [florentpoujol/superpowers-threejs-plugin#2]
I was trying to use this to do some drawing and started getting errors trying to use THREE.PointsMaterial and THREE.Points, I did a diff on the ts files within superpowers game and within this plugin and found that they are very different with lots of things missing in the version in this plugin, did it maybe just pull in an old version?

**Comment by florentpoujol** [comment]
The definitions used by the plugin are indeed quite old and even then they were quite behind the actual state of THREE.js at the time (r73).

Since that time, I updated the definitions on DefinitelyTyped to r74 then r75.

So I should update the plugin to whatever version of THREE.js Superpowers is using (74 or 75 ?) but I actually kind of waited for the release of Sup v1.0 which will (once again) change the structure of the plugins.

Anyway, you could update the plugin yourself by replacing the `typescriptAPI/three.d.ts` file by this one https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/threejs/three.d.ts 
and just rebuild the plugin if you use the sources by typing `npm run build threejs` (I believe... I'am not sure).

**Comment by ken-sands** [comment]
I tried that, (I actually copied the three.d.ts from superpowers so I'd be confident that it was the matching version) but I couldn't get the plugin to build. I got lots of gulp file issues, or file not found, I tried lots of things like moving it into different folders or into a subdirectory of the superpowers source etc. after a couple of hours I got too frustrated and moved onto doing something else in my game. build tools seem to be the bane of my life.
could you guide me through the steps to rebuild the plugin? ie
download it, 
put it [somewhere] 
open command window, 
cd to [somewhere] 
npm run build threejs

**Comment by ken-sands** [comment]
I get this when I try the npn command:
"Task 'threejs' is not in your gulpfile"

**Comment by ken-sands** [comment]
Ahhh!! I just noticed you have a branch with an updated file! that's solved my issues for now. Still it would be really good to know how to rebuild so I can manage updates.

**Comment by florentpoujol** [comment]
Oh right, I forgot about the threer74 branch...
I waited for my pull request on Definitely Typed to be accepted to update the master branch, and by the time it has been done, I forgot.

[From the doc](http://docs.superpowers-html5.com/fr/developpement/extending-superpowers), to build a plugin, you should run the command `npm run build threejs` from Superpowers's root folder, or just `npm run build` from the plugin's folder.

**Comment by ken-sands** [comment]
Okay that seems closer but it still fails with the stuff below, I'm assuming that the version of superpowers and the version of the plugin not tying up. I'll go with you on the wait for v1.0 to look more into the plugins, for now with the updated file from that branch I have the things I wanted to use working. Thanks for your help.

14 verbose stack Error: superpowers@1.0.0 build: `node scripts/build.js "threejs"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid superpowers@1.0.0

**Comment by florentpoujol** [comment]
Closing this issue, since Superpowers v3.0 now uses THREE.js r80.
I just updated the definitions (v0.4.1).
